# Generated by Django 4.2.5 on 2023-10-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='camada_curso',
            new_name='camadaCurso',
        ),
    ]
